import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const birdsPath = join(__dirname, '../src/data/birds.json');

const PLACEHOLDER = '/birds/placeholder.jpg';

const batchBirds = [
  {
    slug: 'black-bellied-whistling-duck',
    commonName: 'Black-bellied Whistling-Duck',
    scientificName: 'Dendrocygna autumnalis',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas', 'Rivers & streams'],
    description:
      'A distinctive long-legged duck with a bright pink bill and coral-red legs. Adults are chestnut below with a black belly patch, gray face, and bold white wing stripe visible in flight. Often perches in trees and feeds in shallow wetlands and rice fields.',
    size: 'Medium-large',
    diet: 'Omnivore',
    funFact: 'Flocks give whistling calls from treetops at dawn and dusk; often seen walking on muddy banks rather than swimming.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Bright pink bill and coral-red legs',
      'Chestnut breast, black belly patch',
      'Bold white wing stripe in flight',
    ],
    voice: 'Clear whistling calls, often from treetops.',
    similarSpecies: [],
  },
  {
    slug: 'muscovy-duck',
    commonName: 'Muscovy Duck',
    scientificName: 'Cairina moschata',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Rivers & streams', 'Agricultural areas', 'Urban areas'],
    description:
      'A large, heavy-bodied duck with a distinctive red facial caruncle on males. Wild-type birds are mostly black with white wing patches; domestic forms vary widely. Perches readily in trees near water.',
    size: 'Large',
    diet: 'Omnivore',
    funFact: 'Often seen along rivers and village ponds; males show prominent red warty facial skin.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Large size, heavy body',
      'Red facial caruncles on male',
      'Dark plumage with white wing patches (wild type)',
    ],
    voice: 'Low hisses and puffing displays; usually quiet.',
    similarSpecies: [],
  },
  {
    slug: 'blue-winged-teal',
    commonName: 'Blue-winged Teal',
    scientificName: 'Spatula discors',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas'],
    description:
      'A small dabbling duck. Breeding males have a white crescent in front of the eye and a speckled blue forewing. Females are mottled brown with a dark eyeline. Common on shallow ponds and flooded fields in winter.',
    size: 'Small',
    diet: 'Omnivore',
    funFact: 'Look for the white crescent on males and powder-blue shoulder patch in flight.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: white crescent in front of eye',
      'Powder-blue forewing patch in flight',
      'Small compact dabbling duck',
    ],
    voice: 'Peeping calls from flocks on wetlands.',
    similarSpecies: ['cinnamon-teal', 'northern-shoveler'],
  },
  {
    slug: 'cinnamon-teal',
    commonName: 'Cinnamon Teal',
    scientificName: 'Spatula cyanoptera',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas'],
    description:
      'A small dabbling duck. Males are rich cinnamon-red with a red eye and dark back; females are mottled brown resembling other teal. Found on shallow freshwater marshes and ponds.',
    size: 'Small',
    diet: 'Omnivore',
    funFact: 'Male cinnamon body and red eye are distinctive among Belize ducks when present.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: rich cinnamon-red body, red eye',
      'Female: warm brown mottling, dark eyeline',
      'Small dabbling duck on shallow wetlands',
    ],
    voice: 'Soft quacking; less vocal than larger ducks.',
    similarSpecies: ['blue-winged-teal'],
  },
  {
    slug: 'northern-shoveler',
    commonName: 'Northern Shoveler',
    scientificName: 'Spatula clypeata',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas'],
    description:
      'A distinctive dabbling duck with an oversized spoon-shaped bill. Breeding males have green head, white breast, and chestnut flanks; females are mottled brown with a large bill. Filters food from shallow water by bill sweeping.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'The enormous bill is the best field mark at any distance.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Oversized spoon-shaped bill',
      'Male: green head, white breast, chestnut sides',
      'Female: large bill, mottled brown',
    ],
    voice: 'Soft quacking; often silent on wintering grounds.',
    similarSpecies: ['blue-winged-teal'],
  },
  {
    slug: 'american-wigeon',
    commonName: 'American Wigeon',
    scientificName: 'Mareca americana',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas'],
    description:
      'A medium-sized dabbling duck. Males have a green eye patch, whitish crown, and pinkish-brown body; females are gray-brown. Often grazes on land and shows a black-bordered white wing patch in flight.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Note the pale crown on males and white forewing in flight on flooded fields and lagoons.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: green eye patch, whitish crown',
      'White wing patch with black trailing edge',
      'Short bluish bill with black tip',
    ],
    voice: 'Soft whistled wheezy calls.',
    similarSpecies: [],
  },
  {
    slug: 'northern-pintail',
    commonName: 'Northern Pintail',
    scientificName: 'Anas acuta',
    family: 'Anatidae',
    habitat: ['Wetlands', 'Lakes', 'Agricultural areas'],
    description:
      'An elegant, slender duck with a long pointed tail. Males have chocolate-brown head, white neck stripe, and gray body; females are mottled brown with a pointed tail. Feeds by dabbling in open shallow wetlands.',
    size: 'Medium-large',
    diet: 'Omnivore',
    funFact: 'Slender shape and long tail distinguish it from other dabbling ducks in flight.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Long pointed tail (both sexes)',
      'Male: brown head, white neck stripe, gray body',
      'Slender graceful profile',
    ],
    voice: 'Soft whistling calls from males; quacking from females.',
    similarSpecies: [],
  },
  {
    slug: 'ring-necked-duck',
    commonName: 'Ring-necked Duck',
    scientificName: 'Aythya collaris',
    family: 'Anatidae',
    habitat: ['Lakes', 'Wetlands'],
    description:
      'A compact diving duck. Males are blackish with a white ring on the bill and gray sides; the chestnut neck ring is usually hidden. Females are brown with a white eyering and pale cheek patch.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Look for the white bill ring on males and peaked head shape when diving on lagoons.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: white ring on bill, black back, gray sides',
      'Peaked head shape',
      'Female: brown with white eyering',
    ],
    voice: 'Quiet grunts; usually silent.',
    similarSpecies: ['lesser-scaup'],
  },
  {
    slug: 'lesser-scaup',
    commonName: 'Lesser Scaup',
    scientificName: 'Aythya affinis',
    family: 'Anatidae',
    habitat: ['Lakes', 'Wetlands'],
    description:
      'A small diving duck. Males have a black head with purple gloss, black breast, and gray back; females are brown with white at the base of the bill. Often forms large rafts on open water in winter.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Rafts on open lagoons; male head can look black or purplish depending on light.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: black head, gray back, small size for Aythya',
      'Female: brown with white at bill base',
      'Peaked rear crown',
    ],
    voice: 'Soft grunts during display; mostly silent in Belize.',
    similarSpecies: ['ring-necked-duck'],
  },
  {
    slug: 'plain-chachalaca',
    commonName: 'Plain Chachalaca',
    scientificName: 'Ortalis vetula',
    family: 'Cracidae',
    habitat: ['Forest edges', 'Secondary forest', 'Scrub & thicket', 'Rivers & streams'],
    description:
      'A long-tailed, chicken-like bird of wooded edges and riparian thickets. Mostly olive-brown with a buff belly and bare red throat skin. Noisy groups run along branches and give loud chorus calls at dawn.',
    size: 'Medium-large',
    diet: 'Omnivore',
    funFact: 'Listen for raucous chachalaca choruses at dawn in river-edge woodland.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Long tail, chicken-like shape',
      'Olive-brown above, buff belly',
      'Bare red throat patch',
    ],
    voice: 'Loud rhythmic chachalaca chorus, especially at dawn.',
    similarSpecies: ['crested-guan'],
  },
  {
    slug: 'black-throated-bobwhite',
    commonName: 'Black-throated Bobwhite',
    scientificName: 'Colinus nigrogularis',
    family: 'Odontophoridae',
    habitat: ['Scrub & thicket', 'Agricultural areas', 'Savanna', 'Open woodland'],
    description:
      'A small round quail of open scrub and field edges. Males have a black throat and eyebrow with buff underparts; females are buffier and more mottled. Usually seen in coveys flushing with whirring wings.',
    size: 'Small',
    diet: 'Omnivore',
    funFact: 'Coveys flush explosively from roadside scrub; male black throat is distinctive.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Male: black throat and eyebrow, buff underparts',
      'Female: buff mottling, no black throat',
      'Small round quail, short crest',
    ],
    voice: 'Clear whistled bob-WHITE calls from males.',
    similarSpecies: ['spotted-wood-quail'],
  },
  {
    slug: 'rock-pigeon',
    commonName: 'Rock Pigeon',
    scientificName: 'Columba livia',
    family: 'Columbidae',
    habitat: ['Urban areas', 'Coastal areas', 'Open areas'],
    description:
      'The familiar feral pigeon of towns and villages. Variable plumage but often blue-gray with two dark wing bars and iridescent neck. Strong direct flight on broad wings.',
    size: 'Medium',
    diet: 'Granivore',
    funFact: 'Common around settlements; wild-type birds show pale wing bars and dark wing tips.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Blue-gray body (typical wild type)',
      'Two black wing bars',
      'Broad rounded tail with dark band',
    ],
    voice: 'Low cooing from rooftops and town squares.',
    similarSpecies: ['red-billed-pigeon', 'pale-vented-pigeon'],
  },
  {
    slug: 'scaled-pigeon',
    commonName: 'Scaled Pigeon',
    scientificName: 'Patagioenas speciosa',
    family: 'Columbidae',
    habitat: ['Forest canopy', 'Forest edges', 'Secondary forest'],
    description:
      'A large forest pigeon. Dark maroon-brown overall with a scaly pattern on the neck and a red bill with pale tip. Often flushed from canopy with loud wing claps.',
    size: 'Medium-large',
    diet: 'Frugivore',
    funFact: 'Listen for wing claps when birds flush from tall forest; scaly neck pattern is distinctive.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Dark maroon-brown plumage',
      'Scaly pattern on neck sides',
      'Red bill with pale tip',
    ],
    voice: 'Deep hooting calls in forest canopy.',
    similarSpecies: ['red-billed-pigeon', 'pale-vented-pigeon'],
  },
  {
    slug: 'white-crowned-pigeon',
    commonName: 'White-crowned Pigeon',
    scientificName: 'Patagioenas leucocephala',
    family: 'Columbidae',
    habitat: ['Coastal areas', 'Mangroves', 'Forest edges'],
    description:
      'A large dark pigeon with a crisp white cap and pale eye. Body is dark gray with iridescent green on the back. Strong flier between coastal mangroves and inland feeding areas.',
    size: 'Medium-large',
    diet: 'Frugivore',
    funFact: 'White crown and pale eye stand out on dark body; often flies high between coast and forest.',
    status: 'Resident',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: [
      'Crisp white crown',
      'Pale iris on dark gray body',
      'Iridescent green on back in good light',
    ],
    voice: 'Low hooting calls; wings audible in flight.',
    similarSpecies: ['red-billed-pigeon'],
  },
  {
    slug: 'red-billed-pigeon',
    commonName: 'Red-billed Pigeon',
    scientificName: 'Patagioenas flavirostris',
    family: 'Columbidae',
    habitat: ['Forest canopy', 'Forest edges', 'Secondary forest'],
    description:
      'A large purple-brown pigeon with a red bill and yellowish tip. Tail is gray without white markings. Common in forest and woodland, often seen flying overhead in pairs.',
    size: 'Medium-large',
    diet: 'Frugivore',
    funFact: 'Purple-brown body and red-and-yellow bill distinguish it from short-billed and pale-vented pigeons.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Purple-brown body',
      'Red bill with yellow tip',
      'Plain gray tail, no white band',
    ],
    voice: 'Low whooing calls from canopy.',
    similarSpecies: ['short-billed-pigeon', 'pale-vented-pigeon', 'scaled-pigeon'],
  },
  {
    slug: 'eurasian-collared-dove',
    commonName: 'Eurasian Collared-Dove',
    scientificName: 'Streptopelia decaocto',
    family: 'Columbidae',
    habitat: ['Urban areas', 'Agricultural areas', 'Open areas', 'Gardens'],
    description:
      'A pale sandy-gray dove with a narrow black collar on the hindneck and a squared tail with white corners in flight. Larger and paler than Common Ground-Dove; spread widely in towns and farmland.',
    size: 'Medium',
    diet: 'Granivore',
    funFact: 'Three-note cooing song and black collar are easy field marks in villages and open country.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Pale sandy-gray plumage',
      'Narrow black collar on hindneck',
      'White tail corners in flight',
    ],
    voice: 'Three-note cooing: cu-COO-coo.',
    similarSpecies: ['mourning-dove', 'white-winged-dove'],
  },
  {
    slug: 'common-ground-dove',
    commonName: 'Common Ground Dove',
    scientificName: 'Columbina passerina',
    family: 'Columbidae',
    habitat: ['Open areas', 'Gardens', 'Agricultural areas', 'Scrub & thicket'],
    description:
      'A tiny dove of open ground and bare paths. Ruddy brown with scaled appearance on the head and breast; short tail shows rufous in flight. Often flushes with whistling wing beats.',
    size: 'Very small',
    diet: 'Granivore',
    funFact: 'Tiny size and scaled plumage distinguish it from Ruddy Ground-Dove on open ground.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Very small dove on the ground',
      'Scaled head and breast pattern',
      'Rufous in wings and tail in flight',
    ],
    voice: 'Soft cooing; wings whistle on flush.',
    similarSpecies: ['ruddy-ground-dove', 'blue-ground-dove'],
  },
  {
    slug: 'ruddy-quail-dove',
    commonName: 'Ruddy Quail-Dove',
    scientificName: 'Geotrygon montana',
    family: 'Columbidae',
    habitat: ['Forest understory', 'Secondary forest', 'Forest edges'],
    description:
      'A shy forest dove walking on the ground. Warm ruddy brown with a pale stripe below the eye and iridescent purple on the back. Usually seen alone, flushing briefly from trails.',
    size: 'Small-medium',
    diet: 'Frugivore',
    funFact: 'Walks quietly on forest floor; brief views when flushed show ruddy body and pale face stripe.',
    status: 'Resident',
    regions: ['Forest interior', 'Countrywide'],
    fieldMarks: [
      'Warm ruddy brown body',
      'Pale stripe below eye',
      'Purple iridescence on back',
    ],
    voice: 'Soft whooing from dense understory.',
    similarSpecies: ['blue-ground-dove'],
  },
  {
    slug: 'white-tipped-dove',
    commonName: 'White-tipped Dove',
    scientificName: 'Leptotila verreauxi',
    family: 'Columbidae',
    habitat: ['Forest edges', 'Secondary forest', 'Gardens', 'Scrub & thicket'],
    description:
      'A large gray-brown ground dove. Shows a white tail tip in flight and has a pale blue orbital ring. Common in woodland edges, gardens, and secondary growth.',
    size: 'Medium',
    diet: 'Frugivore',
    funFact: 'White tail corners flash when it flushes; pale blue eyering visible at close range.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Gray-brown body',
      'White tail tip visible in flight',
      'Pale blue eyering',
    ],
    voice: 'Deep whooing, often repeated from cover.',
    similarSpecies: ['gray-chested-dove'],
  },
  {
    slug: 'white-winged-dove',
    commonName: 'White-winged Dove',
    scientificName: 'Zenaida asiatica',
    family: 'Columbidae',
    habitat: ['Urban areas', 'Scrub & thicket', 'Agricultural areas', 'Forest edges'],
    description:
      'A slender brown dove with a bold white wing patch in flight and blue eyering. Tail is squared with white corners. Common in towns, scrub, and open woodland.',
    size: 'Medium',
    diet: 'Granivore',
    funFact: 'Bold white wing patch in flight and whooing song in settled areas.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Bold white wing patch in flight',
      'Brown body, blue eyering',
      'White tail corners',
    ],
    voice: 'Soft whoo-hoo-HOO-HOO pattern.',
    similarSpecies: ['mourning-dove', 'eurasian-collared-dove'],
  },
  {
    slug: 'mourning-dove',
    commonName: 'Mourning Dove',
    scientificName: 'Zenaida macroura',
    family: 'Columbidae',
    habitat: ['Open areas', 'Agricultural areas', 'Urban areas', 'Scrub & thicket'],
    description:
      'A slim tan-brown dove with a long pointed tail and black spots on the wings. Common in open country and towns. Flight is swift and direct with whistling wing beats.',
    size: 'Medium',
    diet: 'Granivore',
    funFact: 'Long pointed tail and whistling wings on flush; mournful cooing song.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Slim tan-brown body',
      'Long pointed tail',
      'Black spots on wings',
    ],
    voice: 'Mournful cooing: oo-AH cooo cooo.',
    similarSpecies: ['white-winged-dove', 'eurasian-collared-dove'],
  },
  {
    slug: 'striped-cuckoo',
    commonName: 'Striped Cuckoo',
    scientificName: 'Tapera naevia',
    family: 'Cuculidae',
    habitat: ['Scrub & thicket', 'Grassland', 'Agricultural areas', 'Open areas'],
    description:
      'A slender crested cuckoo of open country. Buff below with bold black streaking; long tail and shaggy crest. Often sits conspicuously on fence posts and wires.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Crested profile and streaked underparts; listen for ascending whistled song from open scrub.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: [
      'Shaggy crest',
      'Buff underparts with black streaks',
      'Long graduated tail',
    ],
    voice: 'Ascending whistled series, often from exposed perch.',
    similarSpecies: ['groove-billed-ani'],
  },
  {
    slug: 'yellow-billed-cuckoo',
    commonName: 'Yellow-billed Cuckoo',
    scientificName: 'Coccyzus americanus',
    family: 'Cuculidae',
    habitat: ['Forest edges', 'Secondary forest', 'Open woodland', 'Scrub & thicket'],
    description:
      'A long-tailed brown cuckoo with a yellow lower mandible and bold white tail spots from below. Secretive in foliage but often detected by its knocking call in migration and breeding season.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'White tail spots from below and yellow bill base; listen for slow knocking song.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'Brown above, white below',
      'Yellow lower mandible',
      'Large white tail spots from below',
    ],
    voice: 'Slow knocking cu-cu-cu series.',
    similarSpecies: ['mangrove-cuckoo', 'black-billed-cuckoo', 'common-squirrel-cuckoo'],
  },
  {
    slug: 'mangrove-cuckoo',
    commonName: 'Mangrove Cuckoo',
    scientificName: 'Coccyzus minor',
    family: 'Cuculidae',
    habitat: ['Mangroves', 'Coastal areas', 'Scrub & thicket', 'Forest edges'],
    description:
      'A buff-breasted cuckoo with a black mask, yellow lower mandible, and plain buff undertail. Favors coastal thickets and mangroves but occurs inland in scrub. More often heard than seen.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Black mask and buff breast; guttural gwa calls from dense coastal scrub.',
    status: 'Resident',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: [
      'Black mask through eye',
      'Buff breast, yellow lower mandible',
      'Plain buff undertail (no bold spots)',
    ],
    voice: 'Guttural gwa-gwa-gwa calls.',
    similarSpecies: ['yellow-billed-cuckoo', 'black-billed-cuckoo'],
  },
  {
    slug: 'black-billed-cuckoo',
    commonName: 'Black-billed Cuckoo',
    scientificName: 'Coccyzus erythropthalmus',
    family: 'Cuculidae',
    habitat: ['Forest edges', 'Secondary forest', 'Scrub & thicket'],
    description:
      'A slim brown-and-white cuckoo with a completely black bill and small white tail spots. Red orbital ring is often hidden. Less common than Yellow-billed Cuckoo on migration.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'All-black bill separates it from Yellow-billed; small white tail spots from below.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: [
      'All-black bill',
      'Brown upperparts, white underparts',
      'Small white tail spots (not large patches)',
    ],
    voice: 'Soft cooing and rapid cu-cu-cu when agitated.',
    similarSpecies: ['yellow-billed-cuckoo', 'mangrove-cuckoo'],
  },
];

const birds = JSON.parse(readFileSync(birdsPath, 'utf8'));
const existingSlugs = new Set(birds.map((b) => b.slug));
let nextId = Math.max(...birds.map((b) => b.id)) + 1;

const toAdd = batchBirds
  .filter((bird) => {
    if (existingSlugs.has(bird.slug)) {
      console.warn(`Skipping ${bird.slug} — already in birds.json`);
      return false;
    }
    return true;
  })
  .map((bird) => ({
    ...bird,
    id: nextId++,
    image: PLACEHOLDER,
    audio: `/audio/${bird.slug}.mp3`,
    frequency: '',
  }));

if (toAdd.length === 0) {
  console.log('No new birds to add.');
  process.exit(0);
}

birds.push(...toAdd);
writeFileSync(birdsPath, JSON.stringify(birds, null, 2) + '\n');
console.log(`Added ${toAdd.length} species (ids ${toAdd[0].id}–${toAdd[toAdd.length - 1].id})`);
console.log('Images: placeholder — add species photos in a follow-up pass.');
