import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const birdsPath = join(__dirname, '../src/data/birds.json');

const PLACEHOLDER = '/birds/placeholder.jpg';

const batchBirds = [
  {
    slug: 'marbled-godwit',
    commonName: 'Marbled Godwit',
    scientificName: 'Limosa fedoa',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Wetlands', 'Mudflats'],
    description:
      'A large, elegant shorebird with a very long slightly upturned bill. Breeding plumage is marbled brown and cinnamon; winter birds are gray-brown. Probes deep in mud for invertebrates on coastal lagoons and estuaries.',
    size: 'Large',
    diet: 'Insectivore',
    funFact: 'Long bicolored bill and cinnamon wing linings in flight on coastal mudflats.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Very long slightly upturned bill', 'Marbled brown plumage', 'Cinnamon wing linings in flight'],
    voice: 'Soft ker-wee calls in flight.',
    similarSpecies: ['upland-sandpiper'],
  },
  {
    slug: 'short-billed-dowitcher',
    commonName: 'Short-billed Dowitcher',
    scientificName: 'Limnodromus griseus',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Coastal areas', 'Mudflats'],
    description:
      'A chunky shorebird with a long straight bill, feeding with rapid sewing-machine motion in shallow water. Gray-brown overall with orange underparts in breeding plumage. Often in flocks on mudflats and rice fields.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Rapid up-and-down feeding motion in shallow wetlands; listen for too-too-too flight call.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Long straight bill', 'Chunky body', 'Rapid sewing-machine feeding motion'],
    voice: 'Soft too-too-too in flight.',
    similarSpecies: ['long-billed-dowitcher'],
  },
  {
    slug: 'long-billed-dowitcher',
    commonName: 'Long-billed Dowitcher',
    scientificName: 'Limnodromus scolopaceus',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Coastal areas', 'Agricultural areas'],
    description:
      'Similar to Short-billed Dowitcher but with a longer bill and more often found in freshwater. Gray-brown with orange tones in breeding plumage. Feeds by rapid probing in shallow water.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Longer bill than Short-billed; often on freshwater marshes and flooded fields.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Very long straight bill', 'Gray-brown plumage', 'Sewing-machine feeding motion'],
    voice: 'Keek call; similar to Short-billed.',
    similarSpecies: ['short-billed-dowitcher'],
  },
  {
    slug: 'wilsons-snipe',
    commonName: "Wilson's Snipe",
    scientificName: 'Gallinago delicata',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Marshes', 'Agricultural areas'],
    description:
      'A stocky marsh bird with cryptic striped plumage and a very long bill. Flushes with fast zigzag flight. Winters in wet fields and marsh edges; often heard winnowing display in breeding areas.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Explosive zigzag flush from marsh edge; long bill and striped back.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Very long bill', 'Striped brown back', 'Short tail with orange outer feathers'],
    voice: 'Winnowing display sound from tail feathers; harsh scape when flushed.',
    similarSpecies: [],
  },
  {
    slug: 'wilsons-phalarope',
    commonName: "Wilson's Phalarope",
    scientificName: 'Phalaropus tricolor',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Lakes', 'Coastal areas'],
    description:
      'A dainty shorebird that spins in circles on the water to stir up food. Breeding females are brighter than males. Gray above and white below with a black stripe through the eye in breeding plumage.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Spins on water surface; female brighter and leaves male to incubate.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Spinning feeding behavior', 'Fine needle-like bill', 'Black eye stripe (breeding)'],
    voice: 'Soft wik wik calls.',
    similarSpecies: [],
  },
  {
    slug: 'spotted-sandpiper',
    commonName: 'Spotted Sandpiper',
    scientificName: 'Actitis macularius',
    family: 'Scolopacidae',
    habitat: ['Rivers & streams', 'Wetlands', 'Coastal areas', 'Lakes'],
    description:
      'A small sandpiper that bobs its rear constantly. Breeding adults have bold black spots below; winter birds are plain gray-brown. Common along riverbanks, pond edges, and coastal rocks.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Constant teetering motion; spotted breast in breeding plumage.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Constant body bobbing', 'Spotted underparts (breeding)', 'White wing stripe in flight'],
    voice: 'Peet-wee calls; nervous weet-weet in flight.',
    similarSpecies: ['solitary-sandpiper'],
  },
  {
    slug: 'solitary-sandpiper',
    commonName: 'Solitary Sandpiper',
    scientificName: 'Tringa solitaria',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Forest edges', 'Rivers & streams', 'Lakes'],
    description:
      'A small dark sandpiper of freshwater edges. Dark olive-brown above with fine white spots; white eyering and barred tail visible in flight. Bobs tail like Spotted Sandpiper but darker overall.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Dark sandpiper of pond edges; barred tail and white eyering in flight.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Dark olive-brown above', 'White eyering', 'Barred tail in flight'],
    voice: 'High peet-peet-peet in flight.',
    similarSpecies: ['spotted-sandpiper'],
  },
  {
    slug: 'lesser-yellowlegs',
    commonName: 'Lesser Yellowlegs',
    scientificName: 'Tringa flavipes',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Coastal areas', 'Mudflats', 'Agricultural areas'],
    description:
      'A graceful medium-sized shorebird with bright yellow legs and a medium-length bill. Gray above and white below with fine streaking on the neck. Active feeder in shallow water on mudflats and marshes.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Bright yellow legs and neat medium bill; tu-tu-tu flight call.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Bright yellow legs', 'Medium-length straight bill', 'Gray back, white underparts'],
    voice: 'Tu-tu-tu flight calls.',
    similarSpecies: ['greater-yellowlegs'],
  },
  {
    slug: 'greater-yellowlegs',
    commonName: 'Greater Yellowlegs',
    scientificName: 'Tringa melanoleuca',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Coastal areas', 'Mudflats', 'Lakes'],
    description:
      'A large shorebird with long bright yellow legs and a long slightly upturned bill. Gray above with white underparts and heavy streaking on the breast. Loud and conspicuous on mudflats and marshes.',
    size: 'Medium-large',
    diet: 'Insectivore',
    funFact: 'Larger than Lesser with longer bill; loud three-note flight call.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Long yellow legs', 'Long slightly upturned bill', 'Heavy breast streaking'],
    voice: 'Loud three-note tew-tew-tew.',
    similarSpecies: ['lesser-yellowlegs'],
  },
  {
    slug: 'ruddy-turnstone',
    commonName: 'Ruddy Turnstone',
    scientificName: 'Arenaria interpres',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Rocky shores', 'Mudflats'],
    description:
      'A compact shorebird that flips stones and debris on rocky shores. Breeding plumage is striking rufous, black, and white; winter birds are brown and gray. Short orange legs and wedge-shaped bill.',
    size: 'Small-medium',
    diet: 'Insectivore',
    funFact: 'Flips seaweed and debris on rocky coast; harlequin breeding plumage.',
    status: 'Migrant',
    regions: ['Coastal areas'],
    fieldMarks: ['Calico breeding plumage', 'Short orange legs', 'Black breast band (breeding)'],
    voice: 'Rattling kit-kit-kit in flight.',
    similarSpecies: [],
  },
  {
    slug: 'stilt-sandpiper',
    commonName: 'Stilt Sandpiper',
    scientificName: 'Calidris himantopus',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Mudflats', 'Agricultural areas'],
    description:
      'A medium sandpiper with long yellow-green legs and a long drooping bill. Gray-brown with fine streaking; feeds by probing in shallow water like a small yellowlegs.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Long legs and drooping bill; mixes with dowitchers on shallow wetlands.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Long yellow-green legs', 'Long drooping bill', 'Gray-brown with fine streaking'],
    voice: 'Soft chu calls.',
    similarSpecies: ['lesser-yellowlegs', 'short-billed-dowitcher'],
  },
  {
    slug: 'sanderling',
    commonName: 'Sanderling',
    scientificName: 'Calidris alba',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Sandy beaches'],
    description:
      'A small pale sandpiper that runs back and forth at the wave edge on sandy beaches. Breeding plumage is rufous, black, and white; winter birds are pale gray above and white below. Black bill and legs.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Runs with the surf on sandy beaches; very pale in winter plumage.',
    status: 'Migrant',
    regions: ['Coastal areas'],
    fieldMarks: ['Pale gray and white (winter)', 'Runs along wave line', 'Black bill, black legs'],
    voice: 'Soft kwit kwit in flight.',
    similarSpecies: ['western-sandpiper', 'semipalmated-sandpiper'],
  },
  {
    slug: 'white-rumped-sandpiper',
    commonName: 'White-rumped Sandpiper',
    scientificName: 'Calidris fuscicollis',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Coastal areas', 'Mudflats', 'Agricultural areas'],
    description:
      'A small brown sandpiper with a distinctive white rump patch in flight. Fine streaking on breast; slightly drooping bill. Often in flocks on mudflats and flooded fields in migration.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'White rump flashes in flight; flocks on muddy wetlands in migration.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['White rump in flight', 'Fine breast streaking', 'Slightly drooping bill'],
    voice: 'Soft cherp calls.',
    similarSpecies: ['pectoral-sandpiper', 'least-sandpiper'],
  },
  {
    slug: 'least-sandpiper',
    commonName: 'Least Sandpiper',
    scientificName: 'Calidris minutilla',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Wetlands', 'Mudflats', 'Agricultural areas'],
    description:
      'The smallest shorebird in the Americas. Tiny brown sandpiper with yellow-green legs and a fine dark bill. Pecks at the surface rather than probing deeply. Common on mudflats and pond edges.',
    size: 'Very small',
    diet: 'Insectivore',
    funFact: 'Smallest shorebird; yellow-green legs distinguish it from similar peeps.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Very small size', 'Yellow-green legs', 'Fine dark bill'],
    voice: 'Soft trill in flight.',
    similarSpecies: ['semipalmated-sandpiper', 'western-sandpiper'],
  },
  {
    slug: 'pectoral-sandpiper',
    commonName: 'Pectoral Sandpiper',
    scientificName: 'Calidris melanotos',
    family: 'Scolopacidae',
    habitat: ['Wetlands', 'Mudflats', 'Agricultural areas', 'Coastal areas'],
    description:
      'A medium-small sandpiper with streaked breast ending abruptly at a clean white belly. Yellow-green legs and slightly drooping bill. Breeds in Arctic; winters in South America, passing through Belize.',
    size: 'Small-medium',
    diet: 'Insectivore',
    funFact: 'Sharp boundary between streaked breast and white belly.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Streaked breast with clean white belly cutoff', 'Yellow-green legs', 'Slightly drooping bill'],
    voice: 'Hooting display song on breeding grounds; soft chirps in migration.',
    similarSpecies: ['white-rumped-sandpiper', 'least-sandpiper'],
  },
  {
    slug: 'western-sandpiper',
    commonName: 'Western Sandpiper',
    scientificName: 'Calidris mauri',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Wetlands', 'Mudflats'],
    description:
      'A small sandpiper with a long slightly drooping bill and black legs. Gray-brown above; rufous tones on scapulars in breeding plumage. Often in large flocks on coastal mudflats.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Black legs and long drooping bill among the small Calidris sandpipers.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Black legs', 'Long slightly drooping bill', 'Rufous scapulars (breeding)'],
    voice: 'Soft kreet in flight.',
    similarSpecies: ['semipalmated-sandpiper', 'least-sandpiper'],
  },
  {
    slug: 'semipalmated-sandpiper',
    commonName: 'Semipalmated Sandpiper',
    scientificName: 'Calidris pusilla',
    family: 'Scolopacidae',
    habitat: ['Coastal areas', 'Wetlands', 'Mudflats'],
    description:
      'A small sandpiper with a short straight bill and black legs. Gray-brown above and white below. Toes are slightly webbed. Common in flocks on mudflats during migration.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Short straight bill and black legs; often in dense flocks on mudflats.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Short straight bill', 'Black legs', 'Gray-brown upperparts'],
    voice: 'Chirping flight calls from flocks.',
    similarSpecies: ['western-sandpiper', 'least-sandpiper'],
  },
  {
    slug: 'laughing-gull',
    commonName: 'Laughing Gull',
    scientificName: 'Leucophaeus atricilla',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Wetlands', 'Urban areas', 'Lakes'],
    description:
      'A medium gull with a black head in breeding plumage and a dark red bill. Gray back, white underparts, and dark wings with white trailing edge. Common along coasts, lagoons, and fishing villages.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Black hood and laughing call along coasts and lagoons.',
    status: 'Resident',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Black hood (breeding)', 'Dark red bill', 'Gray back, black wing tips'],
    voice: 'Laughing ha-ha-ha calls.',
    similarSpecies: ['franklins-gull'],
  },
  {
    slug: 'franklins-gull',
    commonName: "Franklin's Gull",
    scientificName: 'Leucophaeus pipixcan',
    family: 'Laridae',
    habitat: ['Wetlands', 'Lakes', 'Coastal areas', 'Agricultural areas'],
    description:
      'A small graceful gull with a black hood in breeding plumage and bold white eye crescents. Dark bill and reddish legs. Often seen in flocks over inland wetlands and rice fields on migration.',
    size: 'Small-medium',
    diet: 'Omnivore',
    funFact: 'Bold white eye arcs on black hood; flocks over inland wetlands in migration.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Black hood with white eye crescents (breeding)', 'Dark bill', 'Reddish legs'],
    voice: 'Karr karr calls from flocks.',
    similarSpecies: ['laughing-gull'],
  },
  {
    slug: 'sooty-tern',
    commonName: 'Sooty Tern',
    scientificName: 'Onychoprion fuscatus',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Open areas'],
    description:
      'A striking pelagic tern with uniform dark brown upperparts and white underparts. Long pointed wings and shallow forked tail. Seen offshore and along the coast, especially after storms.',
    size: 'Medium',
    diet: 'Carnivore',
    funFact: 'Dark above, white below; pelagic species seen along coast and after storms.',
    status: 'Migrant',
    regions: ['Coastal areas'],
    fieldMarks: ['Uniform dark brown upperparts', 'White underparts', 'Shallow forked tail'],
    voice: 'Loud ker-wacky-wack calls at colonies.',
    similarSpecies: [],
  },
  {
    slug: 'least-tern',
    commonName: 'Least Tern',
    scientificName: 'Sternula antillarum',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Rivers & streams', 'Lakes'],
    description:
      'The smallest tern. Pale gray above and white below with a black cap and yellow bill in breeding plumage. Fast direct flight over water; plunge-dives for small fish on coast and rivers.',
    size: 'Very small',
    diet: 'Carnivore',
    funFact: 'Tiny tern with yellow bill; nests on open sandy beaches and sandbars.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Very small tern', 'Black cap (breeding)', 'Yellow bill with black tip'],
    voice: 'High kee-dik calls.',
    similarSpecies: ['forsters-tern'],
  },
  {
    slug: 'gull-billed-tern',
    commonName: 'Gull-billed Tern',
    scientificName: 'Gelochelidon nilotica',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Wetlands', 'Agricultural areas'],
    description:
      'A heavy-billed tern that rarely plunge-dives, instead catching insects and crabs on the wing or ground. Pale gray above, white below, black cap in breeding plumage. Broad wings for a tern.',
    size: 'Medium',
    diet: 'Carnivore',
    funFact: 'Thick black bill unlike other terns; hawks insects over wetlands.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Heavy black bill', 'Pale gray back', 'Black cap (breeding)'],
    voice: 'Grating kyar calls.',
    similarSpecies: ['caspian-tern'],
  },
  {
    slug: 'caspian-tern',
    commonName: 'Caspian Tern',
    scientificName: 'Hydroprogne caspia',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Lakes', 'Rivers & streams'],
    description:
      'The largest tern with a massive red-orange bill and black cap. Pale gray above and white below with a shallow forked tail. Powerful flight over coastal lagoons and large inland water bodies.',
    size: 'Large',
    diet: 'Carnivore',
    funFact: 'Huge red bill and loud harsh calls; largest tern in the region.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Very large size', 'Massive red-orange bill', 'Black cap (breeding)'],
    voice: 'Loud harsh grating calls.',
    similarSpecies: ['gull-billed-tern'],
  },
  {
    slug: 'black-tern',
    commonName: 'Black Tern',
    scientificName: 'Chlidonias niger',
    family: 'Laridae',
    habitat: ['Wetlands', 'Lakes', 'Coastal areas'],
    description:
      'A small dark tern. Breeding adults are sooty black with gray wings; winter birds are gray and white with a dark shoulder patch. Hawks insects over marshes and often seen in loose flocks on migration.',
    size: 'Small',
    diet: 'Carnivore',
    funFact: 'Sooty black in breeding plumage; graceful flight over marshy wetlands.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Sooty black body (breeding)', 'Gray wings', 'Dark shoulder patch (winter)'],
    voice: 'Kik kik calls from flocks.',
    similarSpecies: ['forsters-tern'],
  },
  {
    slug: 'forsters-tern',
    commonName: "Forster's Tern",
    scientificName: 'Sterna forsteri',
    family: 'Laridae',
    habitat: ['Coastal areas', 'Wetlands', 'Lakes'],
    description:
      'A medium tern with a light orange bill and black cap in breeding plumage. Pale gray above and white below with long tail streamers. Hunts over lagoons and marshes with graceful plunge-dives.',
    size: 'Medium',
    diet: 'Carnivore',
    funFact: 'Orange bill and black cap; common on coastal lagoons and estuaries.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Orange bill (breeding)', 'Black cap', 'Pale gray upperparts'],
    voice: 'Harsh kerreck calls.',
    similarSpecies: ['least-tern', 'black-tern'],
  },
];

const birds = JSON.parse(readFileSync(birdsPath, 'utf8'));
const existingSlugs = new Set(birds.map((b) => b.slug));
let nextId = Math.max(...birds.map((b) => b.id)) + 1;

const toAdd = batchBirds
  .filter((bird) => {
    if (existingSlugs.has(bird.slug)) {
      console.warn(`Skipping ${bird.slug} — already in birds.json`);
      return false;
    }
    return true;
  })
  .map((bird) => ({
    ...bird,
    id: nextId++,
    image: PLACEHOLDER,
    audio: `/audio/${bird.slug}.mp3`,
    frequency: '',
  }));

if (toAdd.length === 0) {
  console.log('No new birds to add.');
  process.exit(0);
}

birds.push(...toAdd);
writeFileSync(birdsPath, JSON.stringify(birds, null, 2) + '\n');
console.log(`Added ${toAdd.length} species (ids ${toAdd[0].id}–${toAdd[toAdd.length - 1].id})`);
console.log('Images: placeholder — add species photos in a follow-up pass.');
