import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const birdsPath = join(__dirname, '../src/data/birds.json');

const PLACEHOLDER = '/birds/placeholder.jpg';

const batchBirds = [
  {
    slug: 'lesser-nighthawk',
    commonName: 'Lesser Nighthawk',
    scientificName: 'Chordeiles acutipennis',
    family: 'Caprimulgidae',
    habitat: ['Open areas', 'Agricultural areas', 'Scrub & thicket', 'Urban areas'],
    description:
      'A small nighthawk of open country, often seen hawking insects at dusk over fields and towns. Mottled gray-brown with a white wing bar; male has a white throat. Flight is buoyant and bat-like, usually low over the ground.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Feeds at dusk over open fields and roads; white wing bar flashes in low flight.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Mottled gray-brown plumage', 'White wing bar', 'Male: white throat patch'],
    voice: 'Soft peenting calls at dusk.',
    similarSpecies: ['common-nighthawk'],
  },
  {
    slug: 'common-nighthawk',
    commonName: 'Common Nighthawk',
    scientificName: 'Chordeiles minor',
    family: 'Caprimulgidae',
    habitat: ['Open areas', 'Urban areas', 'Agricultural areas', 'Forest edges'],
    description:
      'A widespread nighthawk with long pointed wings and a white wing patch. Mottled gray with a white throat on males. Often seen at dusk over towns and open woodland, sometimes perching on gravel rooftops.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Bold white wing patches visible in flight at dusk over villages and clearings.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Long pointed wings', 'Bold white wing patch', 'Male: white throat'],
    voice: 'Nasal peent calls; booming display dive in breeding areas.',
    similarSpecies: ['lesser-nighthawk'],
  },
  {
    slug: 'common-pauraque',
    commonName: 'Common Pauraque',
    scientificName: 'Nyctidromus albicollis',
    family: 'Caprimulgidae',
    habitat: ['Scrub & thicket', 'Forest edges', 'Open woodland', 'Agricultural areas'],
    description:
      'A ground-dwelling nightjar of open woodland and scrub. Intricately patterned in browns with a black chest collar and long tail. Sits on dirt roads at night, eyes reflecting red in headlights.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Freezes on forest roads at night; red eyeshine and whirring song at dusk.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Black chest collar', 'Long rufous tail', 'Intricate brown mottling'],
    voice: 'Whirring pauraque song at dusk and dawn.',
    similarSpecies: ['chuck-wills-widow', 'yucatan-nightjar'],
  },
  {
    slug: 'chuck-wills-widow',
    commonName: "Chuck-will's-widow",
    scientificName: 'Antrostomus carolinensis',
    family: 'Caprimulgidae',
    habitat: ['Forest edges', 'Open woodland', 'Scrub & thicket'],
    description:
      'A large nightjar with a big head and wide gape. Cryptically patterned in browns and grays; lacks the pauraque chest collar. Often heard calling from wooded edges on migration and in winter.',
    size: 'Medium-large',
    diet: 'Insectivore',
    funFact: 'Named for its loud chuck-WILL-widow song from wooded edges at night.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Large head, cryptic brown plumage', 'No black chest collar', 'Long rounded tail'],
    voice: 'Loud chuck-WILL-widow song.',
    similarSpecies: ['common-pauraque', 'yucatan-nightjar'],
  },
  {
    slug: 'yucatan-nightjar',
    commonName: 'Yucatan Nightjar',
    scientificName: 'Antrostomus badius',
    family: 'Caprimulgidae',
    habitat: ['Scrub & thicket', 'Dry forest', 'Forest edges'],
    description:
      'A medium nightjar of dry scrub and open pine-oak areas. Warm brown with less contrast than Common Pauraque; male has white tail corners. Endemic to the Yucatan Peninsula including northern Belize.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Look for it in dry scrub of northern Belize; male shows white tail corners in flight.',
    status: 'Resident',
    regions: ['Northern Belize', 'Countrywide'],
    fieldMarks: ['Warm brown cryptic plumage', 'Male: white tail corners', 'No bold chest collar'],
    voice: 'Rapid churring song from scrub at night.',
    similarSpecies: ['common-pauraque', 'chuck-wills-widow'],
  },
  {
    slug: 'chimney-swift',
    commonName: 'Chimney Swift',
    scientificName: 'Chaetura pelagica',
    family: 'Apodidae',
    habitat: ['Urban areas', 'Open areas', 'Forest edges'],
    description:
      'A small dark swift with cigar-shaped body and stiff rapid wingbeats. Tail is short with projecting spines. Often seen in twittering flocks over towns and open country, especially on migration.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Cigar-shaped body and chittering flocks over towns; all-dark except pale throat.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Cigar-shaped body', 'Stiff rapid wingbeats', 'Short tail with spines'],
    voice: 'High chittering calls from feeding flocks.',
    similarSpecies: ['lesser-swallow-tailed-swift'],
  },
  {
    slug: 'ruby-throated-hummingbird',
    commonName: 'Ruby-throated Hummingbird',
    scientificName: 'Archilochus colubris',
    family: 'Trochilidae',
    habitat: ['Forest edges', 'Gardens', 'Open woodland', 'Secondary forest'],
    description:
      'A small hummingbird. Males have an iridescent ruby-red throat and emerald back; females are green above and whitish below. Common on migration and in winter in gardens and forest edge.',
    size: 'Very small',
    diet: 'Nectarivore',
    funFact: 'Male ruby gorget flashes in good light; common winter visitor to flowering gardens.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Male: ruby-red throat, emerald back', 'Female: green above, whitish below', 'Short bill, small size'],
    voice: 'Soft chipping calls; wings hum in flight.',
    similarSpecies: ['rufous-tailed-hummingbird', 'scaly-breasted-hummingbird'],
  },
  {
    slug: 'cinnamon-hummingbird',
    commonName: 'Cinnamon Hummingbird',
    scientificName: 'Amazilia rutila',
    family: 'Trochilidae',
    habitat: ['Scrub & thicket', 'Forest edges', 'Gardens', 'Dry forest'],
    description:
      'A medium-sized hummingbird with bronzy-green upperparts and cinnamon underparts. Red bill with dark tip. Common in dry scrub, gardens, and open woodland throughout the region.',
    size: 'Small',
    diet: 'Nectarivore',
    funFact: 'Cinnamon underparts and red bill make it one of the easier Amazilia hummingbirds to identify.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Cinnamon underparts', 'Bronzy-green back', 'Red bill with dark tip'],
    voice: 'Dry chipping and buzzy song from perches.',
    similarSpecies: ['buff-bellied-hummingbird', 'rufous-tailed-hummingbird'],
  },
  {
    slug: 'buff-bellied-hummingbird',
    commonName: 'Buff-bellied Hummingbird',
    scientificName: 'Amazilia yucatanensis',
    family: 'Trochilidae',
    habitat: ['Forest edges', 'Scrub & thicket', 'Gardens', 'Secondary forest'],
    description:
      'A medium hummingbird with bronzy-green upperparts, buff belly, and rufous tail corners. Red bill. Favors forest edge and flowering trees in the Yucatan region including Belize.',
    size: 'Small',
    diet: 'Nectarivore',
    funFact: 'Rufous tail corners and buff belly distinguish it from Cinnamon Hummingbird.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Buff belly', 'Rufous tail corners', 'Red bill, bronzy-green back'],
    voice: 'Chipping calls and squeaky song from canopy.',
    similarSpecies: ['cinnamon-hummingbird', 'rufous-tailed-hummingbird'],
  },
  {
    slug: 'spotted-rail',
    commonName: 'Spotted Rail',
    scientificName: 'Pardirallus maculatus',
    family: 'Rallidae',
    habitat: ['Wetlands', 'Mangroves', 'Agricultural areas'],
    description:
      'A large secretive rail of marshes and wet fields. Blackish with bold white spotting and a coral-red bill and legs. Rarely seen but sometimes flushes from dense wet grass.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Bold white spots on dark body and coral bill; flushes briefly from wet marsh edge.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Black with bold white spots', 'Coral-red bill and legs', 'Large rail shape'],
    voice: 'Grunting and whinnying calls from dense cover.',
    similarSpecies: ['sora', 'uniform-crake'],
  },
  {
    slug: 'uniform-crake',
    commonName: 'Uniform Crake',
    scientificName: 'Amaurolimnas concolor',
    family: 'Rallidae',
    habitat: ['Wetlands', 'Forest understory', 'Scrub & thicket'],
    description:
      'A plain dark rail of wet thickets and forest floor. Uniform dark brown with a greenish bill; very secretive. More often heard than seen, walking under dense cover near water.',
    size: 'Small-medium',
    diet: 'Omnivore',
    funFact: 'Plain dark rail of wet thickets; listen for whistled calls at dawn.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Uniform dark brown plumage', 'Greenish bill', 'Secretive ground bird'],
    voice: 'Whistled and grunting calls from dense cover.',
    similarSpecies: ['spotted-rail', 'sora'],
  },
  {
    slug: 'sora',
    commonName: 'Sora',
    scientificName: 'Porzana carolina',
    family: 'Rallidae',
    habitat: ['Wetlands', 'Agricultural areas', 'Mangroves'],
    description:
      'A small rail of marshes and wet fields. Brown upperparts, gray face and breast, and black bib on breeding birds. Short yellow bill. Often detected by whinnying call in winter.',
    size: 'Small',
    diet: 'Omnivore',
    funFact: 'Gray face and whinnying call from marsh edges; black bib on breeding plumage.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Gray face and breast', 'Black bib (breeding)', 'Short yellow bill'],
    voice: 'Distinctive whinnying descending call.',
    similarSpecies: ['spotted-rail', 'russet-naped-wood-rail'],
  },
  {
    slug: 'common-gallinule',
    commonName: 'Common Gallinule',
    scientificName: 'Gallinula galeata',
    family: 'Rallidae',
    habitat: ['Wetlands', 'Lakes', 'Mangroves', 'Rivers & streams'],
    description:
      'A medium marsh bird with dark plumage, white flank stripe, and a red frontal shield on the bill. Swims and walks on floating vegetation. Yellow-tipped red bill and greenish legs.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Red shield on bill and white flank stripe on dark body; common on lily pads and marsh edge.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Red frontal shield on bill', 'White flank stripe', 'Dark body, yellow-tipped bill'],
    voice: 'Krek-krek calls and clucking from marshes.',
    similarSpecies: ['purple-gallinule', 'american-coot'],
  },
  {
    slug: 'american-coot',
    commonName: 'American Coot',
    scientificName: 'Fulica americana',
    family: 'Rallidae',
    habitat: ['Lakes', 'Wetlands', 'Agricultural areas'],
    description:
      'A dark duck-like bird with a white bill and frontal shield. Lobed toes, not webbed feet. Swims on open water and grazes on shorelines; often in large flocks in winter.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'White bill and dark body; lobed toes visible when climbing onto banks.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Dark gray body', 'White bill and frontal shield', 'Lobed toes (not webbed)'],
    voice: 'Various clucks and croaks from flocks on water.',
    similarSpecies: ['common-gallinule'],
  },
  {
    slug: 'purple-gallinule',
    commonName: 'Purple Gallinule',
    scientificName: 'Porphyrio martinica',
    family: 'Rallidae',
    habitat: ['Wetlands', 'Mangroves', 'Lakes'],
    description:
      'A spectacular marsh bird with purple-blue plumage, green back, red bill with yellow tip, and huge yellow feet. Climbs on floating vegetation in freshwater marshes and lily pads.',
    size: 'Medium',
    diet: 'Omnivore',
    funFact: 'Iridescent purple-blue body and giant yellow feet on floating vegetation.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Purple-blue body, green back', 'Red bill with yellow tip', 'Large yellow feet'],
    voice: 'Harsh cackling and grunting from marsh cover.',
    similarSpecies: ['common-gallinule'],
  },
  {
    slug: 'sungrebe',
    commonName: 'Sungrebe',
    scientificName: 'Heliornis fulica',
    family: 'Heliornithidae',
    habitat: ['Rivers & streams', 'Wetlands', 'Forest edges'],
    description:
      'A small secretive waterbird of quiet forest streams and ponds. Brown with bold black-and-white striped neck and a striped face pattern. Male has pouches to carry chicks. Rarely seen, slipping into cover.',
    size: 'Small-medium',
    diet: 'Omnivore',
    funFact: 'Striped neck and face on quiet forest ponds; slips into cover when disturbed.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Bold striped neck pattern', 'Striped face', 'Small brown waterbird'],
    voice: 'Soft whistling and clicking from streamside cover.',
    similarSpecies: [],
  },
  {
    slug: 'limpkin',
    commonName: 'Limpkin',
    scientificName: 'Aramus guarauna',
    family: 'Aramidae',
    habitat: ['Wetlands', 'Rivers & streams', 'Lakes', 'Mangroves'],
    description:
      'A large brown wading bird with white spots on the upperparts and a long decurved bill. Walks along marsh edges and streams hunting apple snails. Loud wailing calls carry at night.',
    size: 'Large',
    diet: 'Carnivore',
    funFact: 'Spotted brown body and screaming calls at night; hunts snails along marshy streams.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Brown with white spots', 'Long decurved bill', 'Long legs, heron-like walk'],
    voice: 'Loud wailing and screaming calls, especially at night.',
    similarSpecies: [],
  },
  {
    slug: 'black-necked-stilt',
    commonName: 'Black-necked Stilt',
    scientificName: 'Himantopus mexicanus',
    family: 'Recurvirostridae',
    habitat: ['Wetlands', 'Coastal areas', 'Agricultural areas', 'Lakes'],
    description:
      'A slender black-and-white shorebird with extraordinarily long pink legs and a thin straight black bill. Forages in shallow water on mudflats and rice fields.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Impossibly long pink legs and black-and-white plumage on shallow mudflats.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Black back and neck, white underparts', 'Very long pink legs', 'Thin straight black bill'],
    voice: 'Sharp yapping calls in flight.',
    similarSpecies: ['american-avocet'],
  },
  {
    slug: 'american-avocet',
    commonName: 'American Avocet',
    scientificName: 'Recurvirostra americana',
    family: 'Recurvirostridae',
    habitat: ['Wetlands', 'Coastal areas', 'Lakes'],
    description:
      'A elegant black-and-white shorebird with a unique upturned bill and long bluish legs. Breeding birds have cinnamon on the head and neck. Swings bill side to side while feeding in shallow water.',
    size: 'Medium-large',
    diet: 'Insectivore',
    funFact: 'Upturned bill and graceful feeding motion in shallow lagoons.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Upturned bill', 'Black-and-white body', 'Long bluish legs'],
    voice: 'Soft wheeups and alarm calls.',
    similarSpecies: ['black-necked-stilt'],
  },
  {
    slug: 'black-bellied-plover',
    commonName: 'Black-bellied Plover',
    scientificName: 'Pluvialis squatarola',
    family: 'Charadriidae',
    habitat: ['Coastal areas', 'Wetlands', 'Open areas'],
    description:
      'A large chunky plover. Breeding adults are black below with white cap and black face; winter birds are gray-brown with a black armpit patch in flight. Runs and stops on mudflats and open shores.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Black armpit patch in flight; winter birds gray with bold black-and-white wings.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Chunky plover shape', 'Black armpit patch in flight', 'Winter: gray-brown above'],
    voice: 'Clear whistled calls in flight.',
    similarSpecies: ['american-golden-plover'],
  },
  {
    slug: 'american-golden-plover',
    commonName: 'American Golden-Plover',
    scientificName: 'Pluvialis dominica',
    family: 'Charadriidae',
    habitat: ['Open areas', 'Agricultural areas', 'Grassland', 'Coastal areas'],
    description:
      'A medium plover with golden-spangled upperparts in breeding plumage; winter birds are gray-brown. Slenderer than Black-bellied Plover with no black armpit patch. Often on open fields and airfields.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Golden speckling on back in breeding plumage; gray-brown on open fields in winter.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Golden-spangled upperparts (breeding)', 'Slender build', 'No black armpit patch'],
    voice: 'Melodious whistled calls.',
    similarSpecies: ['black-bellied-plover'],
  },
  {
    slug: 'killdeer',
    commonName: 'Killdeer',
    scientificName: 'Charadrius vociferus',
    family: 'Charadriidae',
    habitat: ['Open areas', 'Agricultural areas', 'Wetlands', 'Urban areas'],
    description:
      'A familiar plover of open ground with two black breast bands and a red eye ring. Runs on lawns, fields, and mudflats; performs broken-wing distraction display near nests.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Two black breast bands and loud kill-DEE calls from open fields and gravel areas.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Two black breast bands', 'Red eye ring', 'Brown upperparts, white underparts'],
    voice: 'Loud kill-DEE kill-DEE calls.',
    similarSpecies: ['semipalmated-plover', 'collared-plover'],
  },
  {
    slug: 'semipalmated-plover',
    commonName: 'Semipalmated Plover',
    scientificName: 'Charadrius semipalmatus',
    family: 'Charadriidae',
    habitat: ['Coastal areas', 'Wetlands', 'Open areas'],
    description:
      'A small dark plover with one black breast band and orange legs. Bill is orange with black tip. Common on mudflats and beaches in winter flocks.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Single breast band and orange legs on mudflats; smaller than Killdeer.',
    status: 'Migrant',
    regions: ['Coastal areas', 'Countrywide'],
    fieldMarks: ['Single black breast band', 'Orange legs', 'Orange bill with black tip'],
    voice: 'Soft chu-wee calls.',
    similarSpecies: ['killdeer', 'collared-plover'],
  },
  {
    slug: 'collared-plover',
    commonName: 'Collared Plover',
    scientificName: 'Anarhynchus collaris',
    family: 'Charadriidae',
    habitat: ['Coastal areas', 'Rivers & streams', 'Open areas', 'Agricultural areas'],
    description:
      'A small pale plover of sandy shores and river bars. Gray-brown above and white below with a narrow black collar across the breast. Pink legs and dark bill.',
    size: 'Small',
    diet: 'Insectivore',
    funFact: 'Narrow black collar and pale sandy appearance on river sandbars and beaches.',
    status: 'Resident',
    regions: ['Countrywide'],
    fieldMarks: ['Narrow black breast collar', 'Pale sandy brown upperparts', 'Pink legs'],
    voice: 'Soft whistled calls.',
    similarSpecies: ['semipalmated-plover', 'killdeer'],
  },
  {
    slug: 'upland-sandpiper',
    commonName: 'Upland Sandpiper',
    scientificName: 'Bartramia longicauda',
    family: 'Scolopacidae',
    habitat: ['Grassland', 'Agricultural areas', 'Open areas', 'Savanna'],
    description:
      'A long-necked sandpiper of open grasslands and airfields. Buffy with dark streaking above, large eye, and small head on a long neck. Flight shows cinnamon wing linings and fluttering style.',
    size: 'Medium',
    diet: 'Insectivore',
    funFact: 'Long neck and fluttering song flight over open fields; cinnamon wing linings in flight.',
    status: 'Migrant',
    regions: ['Countrywide'],
    fieldMarks: ['Long neck, small head', 'Large eye', 'Cinnamon wing linings in flight'],
    voice: 'Wolf-whistle song in display flight over grasslands.',
    similarSpecies: [],
  },
];

const birds = JSON.parse(readFileSync(birdsPath, 'utf8'));
const existingSlugs = new Set(birds.map((b) => b.slug));
let nextId = Math.max(...birds.map((b) => b.id)) + 1;

const toAdd = batchBirds
  .filter((bird) => {
    if (existingSlugs.has(bird.slug)) {
      console.warn(`Skipping ${bird.slug} — already in birds.json`);
      return false;
    }
    return true;
  })
  .map((bird) => ({
    ...bird,
    id: nextId++,
    image: PLACEHOLDER,
    audio: `/audio/${bird.slug}.mp3`,
    frequency: '',
  }));

if (toAdd.length === 0) {
  console.log('No new birds to add.');
  process.exit(0);
}

birds.push(...toAdd);
writeFileSync(birdsPath, JSON.stringify(birds, null, 2) + '\n');
console.log(`Added ${toAdd.length} species (ids ${toAdd[0].id}–${toAdd[toAdd.length - 1].id})`);
console.log('Images: placeholder — add species photos in a follow-up pass.');
